### ISSUE TITLE
Specificity 

### ISSUE THREAD

**Issue by ivoreis** [uswitch/ustyle#197]
I've encountered a while ago some issues with utility classes and ustyle components. I believe we should revisit this and maybe specify some rules / guidelines about how to do this. I know what we have some sort of order / priority loading our stylesheets but it doesn't seem to be consistent.

I propose following something like ITCSS, it might be useful. 

https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/

Any thoughts?

**Comment by ivoreis** [comment]
Quick example but I link this happens with all components and utility classes. 

If we have 
```css
.us-content-group {
    padding-top: 30px;
    padding-bottom: 30px;
}
```

and we want to change the padding top (doesn't matter the reason) we could use: 

```css
.us-padding-top {
    padding-top: 1em;
}
```

Because both have the same specificity and load order .us-padding-top won't work.

What I'm trying to say is that utility classes work well with non ustyle components / elements but if you start mixing both they don't work well together.
