### ISSUE TITLE
YUI Compressor breaks inline SVGs

### ISSUE THREAD

**Issue by annez** [uswitch/ustyle#40]
https://github.com/uswitch/ustyle/blob/master/vendor/assets/stylesheets/ustyle/forms/_select.sass#L36

Our inline SVGs get their strings concatenated with the new YUI compressor. Example output:

``` css
.us-form-select{background-image:url("data:image/svg+xml;utf8,<svgxmlns='http://www.w3.org/2000/svg'width='31'height='10'viewBox='-1003110'><polygonfill='%23fff'points='11,00,05.5,10'/></svg>"),url("data:image/svg+xml;utf8,<svgversion='1.1'xmlns='http://www.w3.org/2000/svg'x='0px'y='0px'width='31px'height='41px'><rectx='0'y='0'fill='#97999a'width='31'height='40'/></svg>")}
```

Which naturally breaks on any normal browser. As this would only get built on production it isn't something you'd notice as developing.

**Solution**

Switch to a base64 encode for now and escape the string later.

For reference, the YUI bug:
https://github.com/yui/yuicompressor/issues/141
