### ISSUE TITLE
%heading-font-print breaking printers

### ISSUE THREAD

**Issue by annez** [uswitch/ustyle#75]
This line

``` scss
%heading-font-print {
  @media print {
    font: {
      family: $heading-font-secondary !important;
      weight: 700 !important;
    };
  }
}
```

Makes printers restart and kernel panic without printing anything. I'm unsure as to why this is happening, but it's probably worth just having a top level `@media print` with the declarations we need, rather than an extend. I think the printer shits itself when it sees so many `@media print` declarations in the stylesheet.
